### ISSUE TITLE
来自huangguoshun的问题

### ISSUE THREAD

**Issue by BadShun** [Rachel030219/Gradle-for-AIDE#2]
你好，我想问一下，aide中gradle的版本太低了，怎么升级？

**Comment by Rachel030219** [comment]
抱歉，因为已经好几年没有用过 AIDE 了（Android Studio 都很少用），所以不是很清楚…

如果 AIDE 自己带了完整的 Gradle 支持的话，也许可以参考 [这篇文章](https://devdeeds.com/update-gradle-plugin-android-studio/) 中的 Method 2，但如果 AIDE 使用的是 built-in 的 Gradle 或者是用其它玄学方法加入的 Gradle 支持，那就没有办法了（

**Comment by BadShun** [comment]
其实是因为我和我的一个小伙伴在共同开发，他运行我的项目是报错了，gradle的版本太高而项目的gradle版本太低

**Comment by Rachel030219** [comment]
@HuangGuoshun 那应该没办法了…移动开发还是不太适合复杂工程，AIDE 也很难跟上最新的 Android / Gradle / Kotlin （如果有）特性，建议尽可能迁移到 AS（
